server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yury-1980/finale-config-docker.git
          clone-on-start: false
          basedir: file://c:/finale-config-docker
