server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          username: yury-1980
          password: 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
          default-label: master
  profiles:
    default: local

logging:
  pattern:
    console: '[%-5level] %d{HH:mm:ss} - %msg%n'
