server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yury-1980/finale-config.git
          clone-on-start: true
          basedir: file://c:/finale-config
          username: yury-1980
          password: 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
          default-label: master

logging:
  pattern:
    console: '[%-5level] %d{HH:mm:ss} - %msg%n'