server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yury-1980/finale-config.git
          clone-on-start: true
          basedir: file://c:/finale-config
          username: yury-1980
          password: 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
          default-label: master
logging:
  pattern:
    console: '[%-5level] %d{HH:mm:ss} - %msg%n'

#server.port=8888
#spring.application.name=config
#
## доступ к git репозиторию
#spring.cloud.config.server.git.uri=git@github.com:yury-1980/finale-config.git
#
## клонировать удаленный git репозиторий в локальный git (чтобы не делать это вручную)
#spring.cloud.config.server.git.clone-on-start=true
## куда будет клонироваться удаленный репозиторий
#spring.cloud.config.server.git.basedir=file://c:/finale-config/finale-config
#
## для private репозитория потребуется логин-token
#spring.cloud.config.server.git.username=yury-1980
#spring.cloud.config.server.git.password=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
#
## название ветки лучше явно уточнить
#spring.cloud.config.server.git.default-label=master
#
## более короткое отображение логов
#logging.pattern.console=[%-5level] %d{HH:mm:ss} - %msg%n
