INSERT INTO public.users (id, user_name, email, password, role)
VALUES (DEFAULT, 'Вася', 'vasya@example.com', '$2a$10$S1LytuFXizplm.xZGmJPK.nE6qQszZKY5JtTvvTBU5mlC7dpJTG6K',
        'ROLE_SUBSCRIBER'::role),
       (DEFAULT, 'Петя', 'petya@example.com', '$2a$10$.uIu08Cdz5hRPwgfm/fEbOmmQ7Xmj0A98duhpTZeknc0WC7YBDJo6',
        'ROLE_JOURNALIST'::role),
       (DEFAULT, 'Маша', 'masha@example.com', '$2a$10$IpGEj7uCf5Sr54QUefJPweaIkjsmktIFNo.PJOw2amBIzav4D2YqG',
        'ROLE_SUBSCRIBER'::role),
       (DEFAULT, 'Саша', 'sasha@example.com', '$2a$10$rLERRjkaNKHC85f7i/moI.rxhr88H9d2.b.nGnplJyiZ3G/4mm9oe',
        'ROLE_JOURNALIST'::role),
       (DEFAULT, 'Света', 'sveta@example.com', '$2a$10$HE.Cs2h96ocCyjd/B.2Sjuvp8o7xF3zX8RlMoC.LA756Yurk8lpfO',
        'ROLE_SUBSCRIBER'::role),
       (DEFAULT, 'Юра', 'yura@example.com', '$2a$10$UytBUO6MT5Km/8UGxRNVWOHFKPapGzfFJSYITatJiSl7zVpztBG.q',
        'ROLE_SUBSCRIBER'::role),
       (DEFAULT, 'Катя', 'katya@example.com', '$2a$10$w8gNAjH.ZKInbatmt0fskeVeAuMHrnyVS8q7o.SvdflGs40Kfp0Li',
        'ROLE_SUBSCRIBER'::role),
       (DEFAULT, 'Ира', 'ira@example.com', '$2a$10$y1Nx/zDeo6BfWje11JCSReVe8NJrXlnAOBt5vpzD.BC0NoIQTuJZy',
        'ROLE_SUBSCRIBER'::role),
       (DEFAULT, 'Вова', 'vova@example.com', '$2a$10$UgHb59qTMIPQD6JQd1XDUulEIGOAdFtIc1JAw4p37kqGaP9fXoG/W',
        'ROLE_SUBSCRIBER'::role),
       (DEFAULT, 'Маргарита', 'margarita@example.com', '$2a$10$gCZ6hdRBGFnDpg1w2K6jCOe2wLLB604zaYmf6UyUvU0MKOveJGz26',
        'ROLE_ADMIN'::role);